name: build
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        ocaml-version: [ '4.06.0' ]
        operating-system: [macos-latest, ubuntu-latest]
        #operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin -n .
    - run: opam depext -yt benchpress
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
    - uses: actions/upload-artifact@master
      with:
        name: benchpress-bin-${{ matrix.operating-system }}-${{ matrix.ocaml-version }}.exe
        path: _build/default/src/bin/benchpress_bin.exe
